### ISSUE TITLE
url bar and search bar

### ISSUE THREAD

**Issue by Mats1st** [rctgamer3/ff2-default#3]
there are some issues when displaying the url bar and the search bar.

e.g.
- the verifying flag is confusing
![verifying](https://cloud.githubusercontent.com/assets/11299402/12277255/b9dfccc4-b97a-11e5-9c98-a6c401ff0487.png)

- In search bar the favicon of search enginge is missing
![unbenannt](https://cloud.githubusercontent.com/assets/11299402/12277338/1ee342c2-b97b-11e5-9898-5324ad02efb3.PNG)

I have compared the behavior with official ff theme.

parameters: 
ff 43.0.4
ff2 theme 1.0.11

**Comment by rctgamer3** [comment]
I know about both bugs, they will be fixed in the next update, v 1.0.12

You seem to be using one or more add-ons that change the url bar (the lock is different and there's a flag in the url bar). Can you let me know what they're called? This way I can also improve compatibility with them.

**Comment by Mats1st** [comment]
yes, maybe the following add-ons will influence the look of my bars:
- Classic Theme Restorer (1.4.6.1) - this will have the main effect on the different look 
--> this is the add-on config I use (you can find an import function in the add-on; on the buttom left "preferences")
[CTRpreferences.txt](https://github.com/rctgamer3/ff2-default/files/88988/CTRpreferences.txt)

- (Classic Toolbar Buttons (1.4.9.5))
- Flagfox (5.1.6)

I thank you very much for your hard work to keep this "old" theme alive!

When do you estimate to release the update?

**Comment by rctgamer3** [comment]
Should be out this week.

**Comment by rctgamer3** [comment]
Favicon in the search bar cannot be fixed without third-party add-ons since the favicon including the option to switch back to the old interface have been removed from Firefox.

**Comment by Mats1st** [comment]
no problem, because it is shown in tab. 
maybe the other issue (verifying flag) can be fixed ...

**Comment by Mats1st** [comment]
phantastic new old look! all known issues are fixed in 12rc1. 
thanks for your hard work! Keep it up!

**Comment by rctgamer3** [comment]
Control panel issue fixed in 1.0.12(rc1), will _try_ to fix the favicon in the search bar in the next version.
