### ISSUE TITLE
about:preferences

### ISSUE THREAD

**Issue by Mats1st** [rctgamer3/ff2-default#4]
Hello rctgamer3,
the ff3-default theme/add-on has some issues in showing the ff-preferences. For e.g. after clicking on "Sync" I get a blank page (expected behavior: overview over Firefox-Account and some sync options).
After clicking on "saved access data" button in "security" menu, it seems a little window opens. But I get only a litte close button (cross) which can be confirmed only by pressing the enter key. The access data window closes completely (expected behavior: overview over all stored access datas included showing passwords after clicking on button "show passwords").

**Comment by rctgamer3** [comment]
Fixed in 1.0.15. Sorry for the late fix.
